"""Initial migration

Revision ID: 03d3ae5f65a8
Revises: 
Create Date: 2024-06-16 18:39:42.237129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d3ae5f65a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankEmiPayments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['meeting_id', 'loan_account_id'])

    with op.batch_alter_table('memberLoanPayments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['meeting_id', 'member_id'])

    with op.batch_alter_table('memberSavingsPayments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['meeting_id', 'member_id'])

    with op.batch_alter_table('otherServiceChargePayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['member_id'])
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otherServiceChargePayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'staff', ['staff_id'], ['id'])
        batch_op.drop_column('member_id')

    with op.batch_alter_table('memberSavingsPayments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('memberLoanPayments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bankEmiPayments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
